# Generated by Django 4.1.7 on 2023-02-21 18:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Syndic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('license_number', models.IntegerField()),
                ('contact_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('syndic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.syndic')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date_of_release', models.DateField()),
                ('syndic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.syndic')),
            ],
        ),
        migrations.CreateModel(
            name='CarModelSyndic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.carmodel')),
                ('syndic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.syndic')),
            ],
            options={
                'unique_together': {('car_model', 'syndic')},
            },
        ),
        migrations.AddField(
            model_name='carmodel',
            name='syndics',
            field=models.ManyToManyField(through='app1.CarModelSyndic', to='app1.syndic'),
        ),
    ]
